apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.deletetask.Deploymentname}}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{.Values.deletetask.appname}}
  template:
    metadata:
      labels:
        app: {{.Values.deletetask.appname}}
    spec:
      containers:
      - name: {{.Values.deletetask.containername}}
        env:
          - name: CONNECTION_STRING
            value: "Driver={ODBC Driver 17 for SQL Server};Server=tcp:cptserver.database.windows.net,1433;Database=cdptdb;Uid=cptiwari;Pwd=Qwerty@12345;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
        image: {{.Values.deletetask.acrname}}/{{.Values.deletetask.imagename}}:{{.Values.deletetask.imagetag}}
        ports:
        - containerPort: {{.Values.deletetask.containerport}}
