apiVersion: v1
kind: Service
metadata:
  name: {{.Values.deletetask.servicename}}
spec:
  type: ClusterIP
  selector:
    app: {{.Values.deletetask.appname}}
  ports:
  - port: {{.Values.deletetask.serviceport}}
    targetPort: {{.Values.deletetask.targetport}}
