apiVersion: v1
kind: Service
metadata:
  name: {{.Values.addtask.servicename}}
spec:
  type: ClusterIP
  selector:
    app: {{.Values.addtask.appname}}
  ports:
  - port: {{.Values.addtask.serviceport}}
    targetPort: {{.Values.addtask.targetport}}
