addtask :
  Deploymentname : add-task
  appname : add-task
  containername : add-task
  acrname : cptacr.azurecr.io
  imagename : addtask-1
  imagetag : latest
  containerport : 8000
  ingressname : add-task-ingress
  servicename : add-task
  serviceport : 80
  targetport : 8000

gettask :
  Deploymentname : get-task
  appname : get-task
  containername : get-task
  acrname : cptacr.azurecr.io
  imagename : gettask-1
  imagetag : latest
  containerport : 8000
  ingressname : get-task-ingress
  servicename : get-task
  serviceport : 80
  targetport : 8000

deletetask :
  Deploymentname : delete-task
  appname : delete-task
  containername : delete-task
  acrname : cptacr.azurecr.io
  imagename : deletetask-1
  imagetag : latest
  containerport : 8000
  ingressname : delete-task-ingress
  servicename : delete-task
  serviceport : 80
  targetport : 8000

frontendtask :
  Deploymentname : frontend-task
  appname : frontend-task
  containername : frontend-task
  acrname : cptacr.azurecr.io
  imagename : frontend-1
  imagetag : latest
  containerport : 8000
  ingressname : frontend-task-ingress
  servicename : frontend-task
  serviceport : 80
  targetport : 8000