apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Values.frontendtask.ingressname}}
spec:
  ingressClassName : nginx
  rules:
  - host: frontendtask.cptiwari.cloud
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{.Values.frontendtask.servicename}}
            port: 
              number: {{.Values.frontendtask.serviceport}}
