apiVersion: v1
kind: Service
metadata:
  name: {{.Values.frontendtask.servicename}}
spec:
  type: ClusterIP
  selector:
    app: {{.Values.frontendtask.appname}}
  ports:
    - port: {{.Values.frontendtask.serviceport}}
      targetPort: {{.Values.frontendtask.targetPort}}
