apiVersion: v1
kind: Service
metadata:
  name: {{.Values.gettask.servicename}}
spec:
  type: ClusterIP
  selector:
    app: {{.Values.gettask.appname}}
  ports:
    - port: {{.Values.gettask.serviceport}}
      targetPort: {{.Values.gettask.targetport}}
